### ISSUE TITLE
urldecode Umlaute

### ISSUE THREAD

**Issue by MeLovesMyTYPO3** [peterbenke/pb_fileinfo#2]
Hi Peter,

thanks for the awesome script! One issue:
Files with Umlauts are not recognized on my system. Don't know if it's my settings or it's a general problem.

To fix these I added a line to check if the file is found when urldecoding, if so, I replace $attr_array['href'].

`if(is_file(PATH_site . urldecode($attr_array['href']))) {`
`     $attr_array['href'] = urldecode($attr_array['href']);`
`}`

`if(is_file(PATH_site . $attr_array['href'])){`
`    $fileInfo = ' ' . str_replace('%s', $this->byteSize(filesize(PATH_site . $attr_array['href'])), $fileInfo);`
`}else{`
`  $fileInfo = '';`
`}`

Maybe you can add this to the extension if you can reprocude the error/solution.

Best regards

**Comment by peterbenke** [comment]
Hi MeLovesMyTYPO3,

is done.
But normally you should not use files with special characters ;-)

Cheers
